apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/devops/nfs/datadir"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
