apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/devops/nfs/datadir-zk-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zk-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
